"""add_indexes_and_constraints

Revision ID: 74c82011f9ab
Revises: 
Create Date: 2026-08-24 16:14:03.575440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74c82011f9ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_event_registration', ['event_id', 'student_id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_recipient_id'), ['recipient_id'], unique=False)

    with op.batch_alter_table('request_histories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_histories_request_id'), ['request_id'], unique=False)

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requests_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requests_student_id'))

    with op.batch_alter_table('request_histories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_histories_request_id'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_id'))

    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.drop_constraint('uq_event_registration', type_='unique')

    # ### end Alembic commands ###
